# Generated by Django 5.1 on 2024-08-12 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_client_userwatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchlist',
            name='watched_clients',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='user',
        ),
        migrations.CreateModel(
            name='ClientRecipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Client-Recipient Pair',
                'verbose_name_plural': 'Client-Recipient Pairs',
                'unique_together': {('client_email', 'recipient_email')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watched_clients', models.ManyToManyField(blank=True, to='tool.clientrecipient')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='UserWatchlist',
        ),
    ]
