# Generated by Django 5.1 on 2024-08-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_remove_userwatchlist_watched_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrecipient',
            name='region',
            field=models.CharField(default='APAC', max_length=20),
        ),
    ]
